/**
 * Phase 4b — Admin Digest live page.
 *
 * Renders the same payload the daily cron emits. Refresh on demand, choose
 * the lookback window (default 24h).
 */
import React, { useEffect, useState, useCallback } from "react";
import { motion } from "framer-motion";
import { Activity, RefreshCw, Loader2, AlertTriangle } from "lucide-react";
import { adminDigestPreview } from "@/lib/api";

function HtmlPanel({ html }) {
    // The backend produces compact Telegram-HTML (b/i/br). Render safely as styled text.
    return (
        <div
            className="font-mono text-[11.5px] leading-relaxed text-white/85 whitespace-pre-wrap"
            data-testid="admin-digest-text"
            // intentional: the digest text is server-generated by us (no user input)
            dangerouslySetInnerHTML={{ __html: html.replaceAll("\n", "<br/>") }}
        />
    );
}

export const AdminDigestPage = () => {
    const [windowHours, setWindowHours] = useState(24);
    const [data, setData] = useState(null);
    const [busy, setBusy] = useState(false);
    const [err, setErr] = useState(null);

    const load = useCallback(async () => {
        setBusy(true); setErr(null);
        try {
            const r = await adminDigestPreview(windowHours);
            setData(r);
        } catch (e) {
            setErr(e?.response?.data?.detail || e?.message || "load failed");
        } finally { setBusy(false); }
    }, [windowHours]);

    useEffect(() => { load(); }, [load]);

    return (
        <div data-testid="admin-digest-page" className="pb-24">
            <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                    <Activity className="w-4 h-4 text-emerald-300" />
                    <h2 className="text-base font-black uppercase tracking-wider text-white/90">Live Digest</h2>
                </div>
                <div className="flex items-center gap-1.5">
                    <div className="inline-flex items-center gap-0.5 bg-cyber-bg/70 border border-white/8 rounded-md p-0.5">
                        {[6, 24, 72, 168].map((h) => (
                            <button key={h}
                                type="button" onClick={() => setWindowHours(h)}
                                data-testid={`digest-window-${h}h`}
                                className={`text-[10px] font-bold uppercase tracking-wider px-2 py-1 rounded transition ${windowHours === h ? "bg-emerald-500/22 text-emerald-200" : "text-white/55 hover:text-white/85"}`}
                            >
                                {h === 168 ? "7d" : `${h}h`}
                            </button>
                        ))}
                    </div>
                    <button onClick={load} disabled={busy} data-testid="digest-refresh-btn"
                        className="inline-flex items-center gap-1 text-[10.5px] font-bold uppercase tracking-wider px-2.5 py-1.5 rounded-md bg-cyber-bg/70 border border-white/10 text-white/65 hover:text-white/90 hover:bg-white/5 disabled:opacity-40">
                        {busy ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
                        Refresh
                    </button>
                </div>
            </div>

            {err && (
                <div className="text-[11.5px] text-red-300 bg-red-500/10 border border-red-500/30 rounded-md px-2.5 py-1.5 inline-flex items-center gap-1.5 mb-2">
                    <AlertTriangle className="w-3.5 h-3.5" /> {err}
                </div>
            )}

            {data && (
                <motion.div initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}
                    className="rounded-xl border border-white/10 bg-cyber-surface/70 p-3.5">
                    <HtmlPanel html={data.text || ""} />
                    <div className="mt-3 grid grid-cols-2 md:grid-cols-3 gap-2 pt-2.5 border-t border-white/8">
                        {Object.entries(data.stats || {}).map(([k, v]) => (
                            <div key={k} className="text-[10.5px] flex items-center justify-between bg-cyber-bg/55 rounded-md px-2 py-1">
                                <span className="text-white/45 truncate">{k.replaceAll("_", " ")}</span>
                                <span className="font-mono text-emerald-200">{typeof v === "number" ? v.toLocaleString(undefined, { maximumFractionDigits: 2 }) : String(v)}</span>
                            </div>
                        ))}
                    </div>
                </motion.div>
            )}
        </div>
    );
};

export default AdminDigestPage;
