"""Phase 6e — Admin endpoints for the Telegram NFT gift deposit queue.

The watcher (`services.gift_deposit_watcher`) drops three kinds of records:

  intents (status):
    pending     — generated by user, no inbound NFT seen yet
    fulfilled   — auto-credited by watcher, NFT now in user's inventory
    expired     — TTL passed without a matching deposit
    unattributed — NFT arrived with no/wrong memo → manual review here

  gift_deposits (raw events):
    one row per inbound NFT seen on the vault. Idempotent via tx_hash.

This router exposes:
  GET  /api/admin/gift-deposits                 — list (status filter)
  POST /api/admin/gift-deposits/{id}/credit     — manually credit an unattributed deposit to {user_id, item_slug}
  POST /api/admin/gift-deposits/test-credit     — DEV: simulate a fulfilled NFT for an intent_id
  POST /api/admin/gift-deposits/{id}/reject     — mark an unattributed deposit as rejected (kept for audit)

All routes require admin-bearer auth (the existing `verify_admin` dependency).
"""
from __future__ import annotations

import secrets
from typing import Optional

from fastapi import APIRouter, Body, Depends, HTTPException, Query
from pydantic import BaseModel, Field

from core.auth import get_admin_or_readonly_support, get_current_user
from core.config import ENABLE_DEV_LOGIN, ENABLE_GIFT_DEPOSITS, is_admin_tid, logger
from core.db import (
    gift_deposit_intents_col,
    gift_deposits_col,
    inventory_col,
    items_col,
    users_col,
)
from core.time_utils import iso, now
from core.ton import static_url

# RBAC: router-level gate lets support staff READ (safe methods) but blocks
# their writes; full admins get everything. Mirrors the main /api/admin router.
router = APIRouter(
    prefix="/api/admin/gift-deposits",
    dependencies=[Depends(get_admin_or_readonly_support)],
)


async def _require_admin(user: dict = Depends(get_current_user)) -> dict:
    """Full-admin gate for write endpoints (credit / reject). Support is read-only."""
    if not is_admin_tid(user.get("telegram_id")):
        raise HTTPException(status_code=403, detail="admin only")
    return user


class GiftDepositAdminRow(BaseModel):
    id: str
    intent_id: Optional[str] = None
    user_id: Optional[str] = None
    user_username: Optional[str] = None
    user_telegram_id: Optional[int] = None
    memo: Optional[str] = None
    tx_hash: Optional[str] = None
    nft_address: Optional[str] = None
    collection_address: Optional[str] = None
    source_address: Optional[str] = None
    item_slug: Optional[str] = None
    item_name: Optional[str] = None
    image_url: Optional[str] = None
    status: str  # pending|fulfilled|unattributed|expired|rejected
    created_at: str


class GiftDepositAdminListOut(BaseModel):
    rows: list[GiftDepositAdminRow]
    counts: dict[str, int]


@router.get("", response_model=GiftDepositAdminListOut)
async def admin_list_gift_deposits(
    status: str = Query("all", pattern=r"^(all|pending|fulfilled|unattributed|expired|rejected)$"),
    limit: int = Query(100, ge=1, le=500),
    # Read access: router-level RBAC gate already allows full admins + read-only support.
) -> GiftDepositAdminListOut:
    q: dict = {}
    if status != "all":
        q["status"] = status

    rows: list[GiftDepositAdminRow] = []
    user_ids: set[str] = set()
    intents_cur = gift_deposit_intents_col.find(q, {"_id": 0}).sort("created_at", -1).limit(limit)
    intents = [d async for d in intents_cur]
    for d in intents:
        if d.get("user_id"):
            user_ids.add(d["user_id"])

    users_map: dict[str, dict] = {}
    if user_ids:
        async for u in users_col.find({"id": {"$in": list(user_ids)}}, {"_id": 0, "id": 1, "username": 1, "telegram_id": 1}):
            users_map[u["id"]] = u

    for d in intents:
        u = users_map.get(d.get("user_id") or "", {})
        rows.append(GiftDepositAdminRow(
            id=d["id"],
            intent_id=d["id"],
            user_id=d.get("user_id"),
            user_username=u.get("username"),
            user_telegram_id=u.get("telegram_id"),
            memo=d.get("memo"),
            tx_hash=d.get("tx_hash"),
            nft_address=d.get("nft_address"),
            collection_address=d.get("collection_address"),
            source_address=d.get("source_address"),
            item_slug=d.get("item_slug"),
            item_name=d.get("item_name"),
            image_url=d.get("image_url"),
            status=d["status"],
            created_at=d["created_at"],
        ))

    counts: dict[str, int] = {}
    async for c in gift_deposit_intents_col.aggregate(
        [{"$group": {"_id": "$status", "n": {"$sum": 1}}}]
    ):
        counts[c["_id"]] = int(c["n"])
    return GiftDepositAdminListOut(rows=rows, counts=counts)


class AdminCreditIn(BaseModel):
    user_id: str = Field(..., min_length=4, max_length=64)
    item_slug: str = Field(..., min_length=2, max_length=64)
    nft_address: Optional[str] = Field(None, max_length=80)


@router.post("/{intent_id}/credit")
async def admin_credit_gift_deposit(
    intent_id: str,
    payload: AdminCreditIn = Body(...),
    admin: dict = Depends(_require_admin),
) -> dict:
    intent = await gift_deposit_intents_col.find_one({"id": intent_id}, {"_id": 0})
    if not intent:
        raise HTTPException(status_code=404, detail="intent not found")
    if intent["status"] == "fulfilled":
        raise HTTPException(status_code=409, detail="already fulfilled")
    item = await items_col.find_one({"slug": payload.item_slug}, {"_id": 0})
    if not item:
        raise HTTPException(status_code=404, detail=f"item slug {payload.item_slug} not found")
    target_user = await users_col.find_one({"id": payload.user_id}, {"_id": 0})
    if not target_user:
        raise HTTPException(status_code=404, detail="target user not found")

    inv_id = secrets.token_hex(12)
    payout = float(item.get("floor_price_ton") or 0.0)
    inv_doc = {
        "id": inv_id,
        "user_id": payload.user_id,
        "item_slug": item["slug"],
        "item_name": item.get("name", item["slug"]),
        "rarity": item.get("rarity", "common"),
        "image_path": item.get("image_path", f"items/{item['slug']}.png"),
        "payout_ton": payout,
        "status": "in_inventory",
        "case_id": "gift_deposit",
        "roll_id": f"gift_{intent_id}",
        "source": "gift_deposit",
        "created_at": iso(now()),
    }
    await inventory_col.insert_one(inv_doc)

    await gift_deposit_intents_col.update_one(
        {"id": intent_id},
        {"$set": {
            "status": "fulfilled",
            "user_id": payload.user_id,
            "item_slug": item["slug"],
            "item_name": item.get("name"),
            "image_url": static_url(item.get("image_path", f"items/{item['slug']}.png")),
            "nft_address": payload.nft_address,
            "fulfilled_at": iso(now()),
            "credited_by_admin": admin["telegram_id"],
            "inventory_id": inv_id,
        }},
    )
    logger.info(
        "gift_deposit: admin credited intent=%s -> user=%s slug=%s admin=%s",
        intent_id, payload.user_id, item["slug"], admin["telegram_id"],
    )
    return {"ok": True, "inventory_id": inv_id, "item_slug": item["slug"], "payout_ton": payout}


class TestCreditIn(BaseModel):
    intent_id: str = Field(..., min_length=4, max_length=64)
    item_slug: str = Field(..., min_length=2, max_length=64)


@router.post("/test-credit")
async def admin_test_credit_gift_deposit(
    payload: TestCreditIn = Body(...),
    admin: dict = Depends(_require_admin),
) -> dict:
    """Simulate the on-chain watcher landing an NFT for the intent.

    Gated behind ENABLE_DEV_LOGIN to keep production safe.
    """
    if not ENABLE_DEV_LOGIN:
        raise HTTPException(status_code=404, detail="test-credit disabled")
    if not ENABLE_GIFT_DEPOSITS:
        raise HTTPException(status_code=503, detail="gift deposits disabled")

    intent = await gift_deposit_intents_col.find_one({"id": payload.intent_id}, {"_id": 0})
    if not intent:
        raise HTTPException(status_code=404, detail="intent not found")
    if intent["status"] == "fulfilled":
        return {"ok": True, "noop": True, "intent_id": intent["id"]}
    if intent["status"] in ("expired", "rejected"):
        raise HTTPException(status_code=409, detail=f"intent is {intent['status']}")

    item = await items_col.find_one({"slug": payload.item_slug}, {"_id": 0})
    if not item:
        raise HTTPException(status_code=404, detail=f"item slug {payload.item_slug} not found")

    fake_tx = "test_" + secrets.token_hex(20)
    # Idempotency guard: never double-credit the same tx_hash
    existing = await gift_deposits_col.find_one({"tx_hash": fake_tx}, {"_id": 0})
    if existing:
        raise HTTPException(status_code=409, detail="duplicate test tx (retry)")

    inv_id = secrets.token_hex(12)
    payout = float(item.get("floor_price_ton") or 0.0)
    inv_doc = {
        "id": inv_id,
        "user_id": intent["user_id"],
        "item_slug": item["slug"],
        "item_name": item.get("name", item["slug"]),
        "rarity": item.get("rarity", "common"),
        "image_path": item.get("image_path", f"items/{item['slug']}.png"),
        "payout_ton": payout,
        "status": "in_inventory",
        "case_id": "gift_deposit",
        "roll_id": f"gift_{intent['id']}",
        "source": "gift_deposit_test",
        "created_at": iso(now()),
    }
    await inventory_col.insert_one(inv_doc)
    await gift_deposits_col.insert_one({
        "id": secrets.token_hex(12),
        "tx_hash": fake_tx,
        "source_address": "test:admin",
        "nft_address": f"test_nft_{secrets.token_hex(8)}",
        "collection_address": item.get("tonapi_collection") or "test:collection",
        "intent_id": intent["id"],
        "user_id": intent["user_id"],
        "item_slug": item["slug"],
        "comment": intent["memo"],
        "credited": True,
        "queued_admin_review": False,
        "created_at": iso(now()),
    })
    await gift_deposit_intents_col.update_one(
        {"id": intent["id"]},
        {"$set": {
            "status": "fulfilled",
            "item_slug": item["slug"],
            "item_name": item.get("name"),
            "image_url": static_url(item.get("image_path", f"items/{item['slug']}.png")),
            "tx_hash": fake_tx,
            "nft_address": inv_doc["item_slug"],
            "fulfilled_at": iso(now()),
            "inventory_id": inv_id,
        }},
    )
    logger.info("gift_deposit TEST-CREDIT intent=%s user=%s slug=%s tx=%s",
                intent["id"], intent["user_id"], item["slug"], fake_tx)
    return {"ok": True, "inventory_id": inv_id, "tx_hash": fake_tx}


@router.post("/{intent_id}/reject")
async def admin_reject_gift_deposit(
    intent_id: str,
    reason: str = Body("", embed=True),
    admin: dict = Depends(_require_admin),
) -> dict:
    intent = await gift_deposit_intents_col.find_one({"id": intent_id}, {"_id": 0})
    if not intent:
        raise HTTPException(status_code=404, detail="intent not found")
    if intent["status"] == "fulfilled":
        raise HTTPException(status_code=409, detail="already fulfilled")
    await gift_deposit_intents_col.update_one(
        {"id": intent_id},
        {"$set": {
            "status": "rejected",
            "rejected_at": iso(now()),
            "rejected_by_admin": admin["telegram_id"],
            "reject_reason": reason[:500] if reason else None,
        }},
    )
    return {"ok": True}
